name: nixage
version: 0.0.0

default-extensions:
  - ApplicativeDo
  - DeriveGeneric
  - FlexibleContexts
  - FlexibleInstances
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - PatternSynonyms
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - TypeFamilies

library:
  source-dirs: lib

  dependencies:
    - base
    - universum

    - aeson
    - aeson-options
    - ansi-wl-pprint
    - containers
    - hnix
    - text
    - unordered-containers
    - yaml

executables:
  nixage:
    source-dirs: cli
    main: Main.hs

    dependencies:
      - base
      - universum

      - nixage

      - directory
      - filepath
      - optparse-applicative
      - process
      - temporary
      - yaml

    ghc-options:
      - -threaded

data-dir: .
data-files:
  - default.nix
  - project.nix
  - package.yaml
  - cli/*.hs
  - lib/Nixage/*.hs
  - lib/Nixage/Convert/*.hs
  - lib/Nixage/Project/*.hs
  - nix/*.nix
  - nix/extraDeps/*.nix
  - nix/tools/nix-prefetch-git
  - data/stack-shell.nix
