name: nixage
version: 0.0.0

default-extensions:
  - ApplicativeDo
  - DeriveGeneric
  - FlexibleContexts
  - FlexibleInstances
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - PatternSynonyms
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - TypeFamilies

library:
  source-dirs: lib

  dependencies:
    - base

    - aeson
    - aeson-options
    - containers
    - text
    - universum

executables:
  nixage:
    source-dirs: cli
    main: Main.hs

    dependencies:
      - base

      - universum
      - yaml

      - nixage


    ghc-options:
      - -threaded
