name: nixage
version: 0.0.0

default-extensions:
  - ApplicativeDo
  - DeriveGeneric
  - FlexibleContexts
  - FlexibleInstances
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - PatternSynonyms
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - TypeFamilies

library:
  source-dirs: lib

  dependencies:
    - base
    - universum

    - aeson
    - aeson-options
    - ansi-wl-pprint
    - containers
    - hnix
    - smallcheck
    - text
    - unordered-containers
    - yaml

executables:
  nixage:
    source-dirs: cli
    main: Main.hs

    dependencies:
      - base
      - universum

      - nixage

      - directory
      - optparse-applicative
      - process
      - temporary
      - yaml

    ghc-options:
      - -threaded


tests:
  nixage-test:
    main:                Test.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - universum

    - nixage

    - bytestring
    - filepath
    - tasty
    - tasty-golden
    - tasty-smallcheck
    - yaml

data-dir: data
data-files: stack-shell.nix
